version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ssh
  webssh.cyrhades.fr:
    build: webssh
    ports:
    - ${PORT}:8888
  el-gamal-fait-2.cyrhades.fr:
    image: anssi/fcsc2024-crypto-el-gamal-fait-2:latest
    ports:
      - ${PORT_SSH}:4000